CPP = g++
TARGET = scourge
include objects.mk
CFLAGS = `sdl-config --cflags` -Isrc -I/usr/X11R6/include -c -g -Wno-deprecated 
LDFLAGS = `sdl-config --libs` -L/usr/X11R6/lib -lGL -lGLU -lglut -lm -lXmu -lXext -lX11 -lXi



.SUFFIXES : .o .cpp

.cpp.o :
	$(CPP) $(CFLAGS) $< -o $*.o

all: $(TARGET)

$(TARGET): ${OBJS}
	$(CPP) -o $@ ${OBJS} $(LDFLAGS)

clean:
	rm -f $(TARGET) ${OBJS} core

