CPP = g++
TARGET = scourge.exe
include objects.mk
CFLAGS = `sdl-config --prefix= --cflags` -Isrc -Wno-deprecated -c -g
LDFLAGS = `sdl-config --prefix= --libs` -L/usr/X11R6/lib -lm -lopengl32 -lglu32 -lglut32



.SUFFIXES : .o .cpp

.cpp.o :
	$(CPP) $(CFLAGS) $< -o $*.o

all: $(TARGET)
		
$(TARGET): ${OBJS}
	$(CPP) -o $@ ${OBJS} $(LDFLAGS)

clean:
	rm -f $(TARGET) ${OBJS} core

